title: Josh Atwal
logo: /assets/img/profile_image.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer and Data Scientist
  <br><br>
  <b>Please hire me</b>
show_downloads: false
google_analytics: G-1NZV7CL3RW
theme: jekyll-theme-minimal
